version: "3.9"
services:
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5435:5432"
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
    ports:
      - "127.0.0.1:3306:3306"
  mongo:
    image: bitnami/mongodb:3.6.11
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms64m -Xmx64m"
    ports:
      - "127.0.0.1:9200:9200"
  redis:
    image: redis:4.0-alpine
    ports:
      - "127.0.0.1:6379:6379"
  httpserver:
    build:
      context: .
    ports:
      - "8080:8080"
  dynamodb:
    image: amazon/dynamodb-local:1.13.4
    ports:
      - "8000:8000"