export enum OperationsType {
    RESPONSE = 'RESPONSE',
    REQUEST = 'REQUEST',
    QUERY = 'QUERY',
    POSTGRES_QUERY = 'POSTGRES_QUERY',
    MYSQL_QUERY = 'MYSQL_QUERY',
    MONGODB_QUERY = 'MONGODB_QUERY',
    ENVIRONMENT = 'ENVIRONMENT',
    LAMBDA = 'LAMBDA',
    CUSTOM = 'CUSTOM'
}