version: "3.9"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
    ports:
      - "127.0.0.1:3306:3306"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
