POST http://localhost:9000
Content-Type: application/json

{
  "num": 18
}

###

POST http://localhost:9000/send?var1=123&page=2
Content-Type: application/json

{
  "num": 18
}

###

POST http://localhost:9000
Content-Type: application/json

###
